import { Space_Grotesk } from "next/font/google";

import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

// here is the font i want to use in my project

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Available weights
  display: "swap", // Recommended for better performance
  variable: "--font-space-grotesk" // Optional: for Tailwind integration
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={spaceGrotesk.className}
      >
        <Provider>{children}</Provider>
        <Toaster/>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
