import { VT323 } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

// here is the font i want to use in my project

const press_font = VT323({
  subsets: ["latin"],
  weight: "400" // Specify the only available weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={press_font.className}
      >
        <Provider>{children}</Provider>
        <Toaster/>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
